name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # tiap hari
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate snake.svg
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: darksodius
          outputs: |
            dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
